// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgMrxAXhhHsBQ3YDP0fgyJIuXpEY0miw8',
    appId: '1:371038003203:android:8e687c6ff763af0a7c2e36',
    messagingSenderId: '371038003203',
    projectId: 'regal-operand-451709-f4',
    storageBucket: 'regal-operand-451709-f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3c98B9Ejgd1MC5LXmvg2fZcFGE6gJj04',
    appId: '1:371038003203:ios:a8bbed5e8c8a818a7c2e36',
    messagingSenderId: '371038003203',
    projectId: 'regal-operand-451709-f4',
    storageBucket: 'regal-operand-451709-f4.firebasestorage.app',
    iosClientId: '371038003203-0fd1j7su17dr5btqf9cu7ppoksmg2bst.apps.googleusercontent.com',
    iosBundleId: 'com.olivebagel.besetter',
  );

}